### ISSUE TITLE
Correct link to mpss-modules for CentOS 8.5

### ISSUE THREAD

**Issue by Deftaudio** [jjkeijser/mpss#1]
Hi, would you please post the link to RPMs to get KNC running under CentOS8.5? By some reason I only see up to 8.4. 
Did you also get the chance to test it with Rocky 8.5? 
Thank you

**Comment by jjkeijser** [comment]
The release files have been updated - I had built and checked the RPMs under CentOS 8.5 a while ago, but did not properly upload them. The releases for RHEL 8.4 and 8.5 now have the right RPMs for both KNC and KNL.

And no, I have not tested it with Rocky 8.5 yet, but I do not expect any issues, really. I plan to upgrade/migrate my CentOS 8.5 to Rocky Linux soon, so I will post a comment if I do run into any problems.

**Comment by Deftaudio** [comment]
Thank you for sharing this. Looking forward to see your results with Rocky. I'll also try to build from source myself.

**Comment by jjkeijser** [comment]
I've just added the source RPM for the mpss modules - that is easiest to rebuild. Closing this issue.

**Comment by Deftaudio** [comment]
Hi
I've just tried to deploy RPM on the CentOS 8.5 and I'm a bit confused. 
I previously installed and know how to run KNC on 7.4.
Your mpss-module is linked to other mpss packages and I'm not sure what's the proper order of the installation. I tried to do following. I installed fresh CentOS 8.5 and converted it to stream repo, then installed with original 3.8.6 mpss package for other kernel 4.x modules, and then attempted to install your module. I'm quite sure I did something wrong and I appreciate your guidance there. Also, I didn't get there yet, but having networking details due to CentOS 8 change would be good. I'm confused how should I setup network bridge there. 
Thank you!

**Comment by jjkeijser** [comment]
something went wrong there - the package you need is `mpss-modules-4.18.0-305.3.1.el8.x86_64-3.8.6-6.x86_64` and it does not depend on any of the other mpss stuff:
```
rpm -q --requires mpss-modules-4.18.0-305.3.1.el8.x86_64-3.8.6-6.x86_64
/bin/sh
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
```

Plus, there never was a kernel 4.x module package for the mpss 3.8.6 stack (not for a CentOS/RH kernel anyways).  So my advice is to uninstall all mpss packages, and start over.

**Comment by Deftaudio** [comment]
You were right, I accidentally also copied kmod which is only needed for KNL and it had that dependency. 

So, I started from scratch, took 3.8.6 package and didn't copy anything from `modules` directory. Instead I put the proper `mpss-modules-4.18.0-305.3.1.el8.x86_64-3.8.6-6.x86_64` and installed RPMs.
Upon to installation `mic.ko `resulted in different directory `4.18.0-348.2.1.el8_5.x86_64` instead of `4.18.0-348.el8.x86_64`. So I copied it there and ran `depmod -a` after that `modprobe mic` worked just fine. However, I'm still unable to start mpss service: 
```
[root@localhost ~]# systemctl status mpss.service
● mpss.service - Intel(R) MPSS control service
   Loaded: loaded (/etc/systemd/system/mpss.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2022-02-11 18:14:57 EST; 36s ago
  Process: 4469 ExecStart=/etc/init.d/mpss start (code=exited, status=6)

Feb 11 18:14:57 localhost.localdomain systemd[1]: Starting Intel(R) MPSS control service...
Feb 11 18:14:57 localhost.localdomain mpss[4469]: Loading MIC module: [  OK  ]
Feb 11 18:14:57 localhost.localdomain systemd[1]: mpss.service: Control process exited, code=exited status=6
Feb 11 18:14:57 localhost.localdomain systemd[1]: mpss.service: Failed with result 'exit-code'.
Feb 11 18:14:57 localhost.localdomain systemd[1]: Failed to start Intel(R) MPSS control service.
```
Interestingly I also see a flow of PCIe Correctable errors but it seems to have nothing to the port where Phi is connected and coming from the root port. That's surprising I don't remember seeing it under 7.4:
```
[  217.682293] pcieport 0000:00:01.0:   device [8086:6f02] error status/mask=00100000/00000000
[  217.682296] pcieport 0000:00:01.0:    [20] UnsupReq               (First)
[  217.682300] pcieport 0000:00:01.0:   TLP Header: 34000000 01000010 00000000 80008000
[  217.682365] pcieport 0000:00:01.0: device recovery successful
[  218.252880] pcieport 0000:00:01.0: Multiple Uncorrected (Non-Fatal) error received: 0000:00:01.0
[  218.252976] pcieport 0000:00:01.0: PCIe Bus Error: severity=Uncorrected (Non-Fatal), type=Transaction Layer, (Requester ID)
[  218.252982] pcieport 0000:00:01.0:   device [8086:6f02] error status/mask=00100000/00000000
[  218.252985] pcieport 0000:00:01.0:    [20] UnsupReq               (First)
[  218.252989] pcieport 0000:00:01.0:   TLP Header: 34000000 01000010 00000000 80008000
[  218.253037] pcieport 0000:00:01.0: device recovery successful

```

**Comment by jjkeijser** [comment]
hmmmm dont know about the PCIe error - but I do know that the PCIe error reporting changed drastically with the Linux kernel 4+.

As for mpssd not running: I'm afraid you're debugging my "switch to github" on this one.  Check out my original page
  https://www.nikhef.nl/~janjust/mpss/xeon-phi-mpss-centos8.html

which lists a patch to the mpss-daemon code, including RPM
  https://www.nikhef.nl/~janjust/mpss/mpss-daemon-3.8.6-4.el8.x86_64.rpm

I think I did check in the patch into github but I may not have released the updated mpss-daemon RPM on github. I will check tomorrow morning and update it there.
