### ISSUE TITLE
micflash failed on "mic0: No valid image found"

### ISSUE THREAD

**Issue by knight110001** [jjkeijser/mpss#2]
Hi jjkeijser,
Thanks for your great work! After applied the release  modules for CentOS 7.9, the "micctrl -s" can get the mic0 ready status, but the "micflash -update -device all" returns the error as following, but there are 5 files in the /usr/share/mpss/flash. Could you pls. give me some advice about this issue? Thanks in advance!

No image path specified - Searching: /usr/share/mpss/flash
mic0: No valid image found

mic0: No valid image found

**Comment by jjkeijser** [comment]
Indeed there should be 5 files listed, one bootloade file and 4 files for each of the different steppings of the Xeon Phi x100:
```
  EXT_HP2_A0_0391-02.rom.smc
  EXT_HP2_B0_0391-02.rom.smc
  EXT_HP2_B1_0391-02.rom.smc
  EXT_HP2_C0_0391-02.rom.smc
  EXT_HP2_SMC_Bootloader_1_8_4326.css_ab
```

Please post the output of 
```
  micinfo -deviceInfo 0
```

(it's the `Coprocessor Stepping` part I am interested in)

**Comment by knight110001** [comment]
Many thanks for reply, after cold reboot several times, it can be flashed and succeeded in lucky, it is very interesting.

MicInfo Utility Log
Created Tue Mar 22 07:00:42 2022


	System Info
		HOST OS			: Linux
		OS Version		: 3.10.0-1160.el7.x86_64
		Driver Version		: 3.8.6-1
		MPSS Version		: 3.8.6

		Host Physical Memory	: 1535754 MB

Device No: 0, Device Name: mic0

	Version
		Flash Version 		 : 2.1.02.0391
		SMC Firmware Version	 : 1.17.6900
		SMC Boot Loader Version	 : 1.8.4326
		Coprocessor OS Version 	 : 2.6.38.8+mpss3.8.6
		Device Serial Number 	 : ADKC51100180

	Board
		Vendor ID 		 : 0x8086
		Device ID 		 : 0x225c
		Subsystem ID 		 : 0x7d95
		Coprocessor Stepping ID	 : 2
		PCIe Width 		 : x8
		PCIe Speed 		 : 5 GT/s
		PCIe Max payload size	 : 256 bytes
		PCIe Max read req size	 : 512 bytes
		Coprocessor Model	 : 0x01
		Coprocessor Model Ext	 : 0x00
		Coprocessor Type	 : 0x00
		Coprocessor Family	 : 0x0b
		Coprocessor Family Ext	 : 0x00
		Coprocessor Stepping 	 : C0
		Board SKU 		 : C0PRQ-7120 P/A/X/D
		ECC Mode 		 : Enabled
		SMC HW Revision 	 : Product 300W Passive CS

	Cores
		Total No of Active Cores : 61
		Voltage 		 : 970000 uV
		Frequency		 : 1238095 kHz

	Thermal
		Fan Speed Control 	 : N/A
		Fan RPM 		 : N/A
		Fan PWM 		 : N/A
		Die Temp		 : 45 C

	GDDR
		GDDR Vendor		 : Samsung
		GDDR Version		 : 0x6
		GDDR Density		 : 4096 Mb
		GDDR Size		 : 15872 MB
		GDDR Technology		 : GDDR5 
		GDDR Speed		 : 5.500000 GT/s 
		GDDR Frequency		 : 2750000 kHz
		GDDR Voltage		 : 1501000 uV

**Comment by jjkeijser** [comment]
I'd recommend to do some stress-testing of the card (e.g. run an OpenCL or OpenMP benchmark) - this *might* mean that your card has power draw or cooling issues (which are not uncommon with the Xeon Phis).
