### ISSUE TITLE
No rule to make target `modules'

### ISSUE THREAD

**Issue by misakina** [jjkeijser/mpss#4]
The following message is displayed when the make command is executed on CentOS7.

[root@ubuntu mpss-modules]# make MIC_CARD_ARCH=k1om KERNEL_VERSION=3.10.0-1160.el7.x86_64 prefix=/usr sysconfdir=/etc
make -C /lib/modules/3.10.0-1160.el7.x86_64/build M=/root/mpss-main/mpss3/mpss-modules modules \
        INSTALL_MOD_PATH=
make[1]: Entering directory `/usr/src/kernels/3.10.0-1160.el7.x86_64'
make[1]: *** No rule to make target `modules'.  Stop.
make[1]: Leaving directory `/usr/src/kernels/3.10.0-1160.el7.x86_64'.
make: *** [modules] Error 2

What should I do?

Best regards.

**Comment by jjkeijser** [comment]
nice to read you solved it yourself - I didn't have time to look at it yet.
