### ISSUE TITLE
Missing tarballs

### ISSUE THREAD

**Issue by PushPioneer** [jjkeijser/mpss#7]
Hi,
does anyone have a copy of ``mpss-modules-3.8.6.tar.bz2``? I can't find them anywhere on the internet.

**Comment by jjkeijser** [comment]
It's not possible to upload .tar.bz2 files here; you should be able to find `mpss-modules-3.8.6.tar.bz2` by looking for `mpss-3.8.6-linux.tar` , then extract  `mpss-3.8.6/src/mpss-modules-3.8.6-1.src.rpm` from it; the .tar.bz2 file is inside the source RPM.

Alternatively you can pretty much recreate the contents of the .tar.bz2 file by doing a checkout of the code in my `mpss3` repo.

**Comment by PushPioneer** [comment]
Thanks for the info
