### ISSUE TITLE
Missing so file

### ISSUE THREAD

**Issue by PushPioneer** [jjkeijser/mpss#8]
I installed the MPSS Software Stack on my Ubuntu 18.04 machine using Kernel 4.15.0-213-generic.
When trying to run `micctrl` I get the following error:

`micctrl: error while loading shared libraries: libmpssconfig.so.0.0.1: cannot open shared object file: No such file or directory`

Did I miss something while installing the MPSS Software Stack?

I followed the exact steps at [https://jjkeijser.github.io/mpss/xeon-phi-mpss-ubuntu.html](https://jjkeijser.github.io/mpss/xeon-phi-mpss-ubuntu.html)

What would help me fix this? Would I need to install the exact same kernel as in the tutorial (4.15.0-122-generic)?
Any help is appreciated.

**Comment by jjkeijser** [comment]
can you try to locate the library ?  my bet is it ended up in /usr/lib64 and that your Ubuntu setup does not look in that directory for shared libraries. If so, then do
  `export LD_LIBRARY_PATH=/usr/lib64:$LD_LIBRARY_PATH`
prior to running `micctrl`

**Comment by PushPioneer** [comment]
Yes, it actually was in /usr/lib46. After running the command I was prompted with a new error `micctrl: error while loading shared libraries: libscif.so.0: cannot open shared object file: No such file or directory`. When running `sudo find -name "libscif.so.0"` it won't find that shares object file. So it doesn't exist on my system. Is there some way to get that  .so file?

**Comment by jjkeijser** [comment]
in the list of mpss-3.8.6 RPMs there is an rpm named `libscif*`   - all packages with a name starting with `lib*` should also be converted to .debs and installed.

**Comment by PushPioneer** [comment]
What RPMs do you mean specifically?

**Comment by jjkeijser** [comment]
in the tarball `mpss-3.8.6-linux.tar` there is an rpm `mpss-3.8.6/libscif0-3.8.6-1.glibc2.12.x86_64.rpm`   
that RPM needs to be converted to a Debian package and installed as well (or you need to extract the contents of the rpm)

**Comment by PushPioneer** [comment]
Where can in find that tarball?
Looking through everything all i could find are these tarballs: `mpss-modules-3.8.6.tar.bz2`, `mpss-daemon-3.8.6.tar.bz2`
Although i found a folder called `libscif` containing a Makefile. After trying to run the `make` command  i was greeted by the following error:
```
gcc -g  -I/home/phi/Downloads/libscif  -fpic -shared scif_api.c -DMPSS_COMMIT=\"'ae50a58d703d3f549c5fbae11ebea950f9f2a059'\" -DMPSS_VERSION=\"'3.6.1-1'\" -DMPSS_BUILDNO=\"'0'\" -DMPSS_BUILTBY=\"'phi@phi'\" -DMPSS_BUILTON=\"'2024-11-24 13:47:07 +0100'\" ./mpss-metadata.c -o libscif.so \
	-Wl,-soname,libscif.so.0 \
	-Wl,--version-script=libscif.map
scif_api.c:50:10: fatal error: scif_ioctl.h: No such file or directory
 #include "scif_ioctl.h"
          ^~~~~~~~~~~~~~
compilation terminated.
Makefile:85: recipe for target 'libscif.so' failed
make: *** [libscif.so] Error 1
``` 
Which I concludes must be becaude `scif_ioctl.h` isn't in `/usr/include/`.
After copping `scif_ioctl.h` (which i got from `mpss-modules-3.8.6-7.src.rpm`) to `/usr/include/` and running the make command again I got another new error:

```
gcc -g  -I/home/phi/Downloads/libscif  -fpic -shared scif_api.c -DMPSS_COMMIT=\"'ae50a58d703d3f549c5fbae11ebea950f9f2a059'\" -DMPSS_VERSION=\"'3.6.1-1'\" -DMPSS_BUILDNO=\"'0'\" -DMPSS_BUILTBY=\"'root@phi'\" -DMPSS_BUILTON=\"'2024-11-24 13:56:30 +0100'\" ./mpss-metadata.c -o libscif.so \
	-Wl,-soname,libscif.so.0 \
	-Wl,--version-script=libscif.map
/usr/bin/ld:libscif.map:0: syntax error in VERSION script
collect2: error: ld returned 1 exit status
Makefile:85: recipe for target 'libscif.so' failed
make: *** [libscif.so] Error 1
```
`libscif.map` contains nothing
Is there something I can do to fix that issue?
And where can i find that tarball (mpss-3.8.6-linux.tar)?

**Comment by jjkeijser** [comment]
I found it using google, e.g. at https://archive.org/details/intel-mpss-3.8.6
I cannot attached an RPM file here

**Comment by PushPioneer** [comment]
After converting the RPM's to deb files and installing them and running `micctrl` I now get the following error: `micctrl: symbol lookup error: micctrl: undefined symbol: _Z12mpssenv_initP8mpss_env`. Did I do something wrong?

**Comment by jjkeijser** [comment]
you also need `libmpssconfig.so.0.0.1 from `mpss-core-3.8.6-1.glibc2.12.x86_64.rpm`  - did you use that version?

This set of RPMs works for me on Rocky Linux and Fedora - I don't have a Ubuntu 18 system to test it with.

**Comment by PushPioneer** [comment]
I used the `libmpssconfig.so.0.0.1` from the mpss-daemon RPM
`mpss-core-3.8.6-1.glibc2.12.x86_64.rpm` is empty (does not contain `libmpssconfig.so.0.0.1`)

**Comment by jjkeijser** [comment]
I extracted the files using `rpm2cpio ... | cpio -id` on Ubuntu  and ran the command
   `LD_LIBRARY_PATH=usr/lib64 usr/sbin/micctrl`

which worked fine for me - did you set the right LD_LIBRARY_PATH?  This has little to do with my page/patches, only with getting the stuff to run on Ubuntu  ...

**Comment by PushPioneer** [comment]
When running `rpm2cpio mpss-core-3.8.6-1.glibc2.12.x86_64.rpm | cpio -id` i get `1 block`. After running `ls` there is nothing new.

When opening the RPM file using the filemanager, it doesn't show any file inside the RPM ![see image](https://github.com/user-attachments/assets/b4c3ed39-2095-4825-87eb-986714ab037b)

**Comment by jjkeijser-10x** [comment]
Try
```
 rpm2cpio libscif0-3.8.6-1.glibc2.12.x86_64.rpm | cpio -id
 rpm2cpio mpss-daemon-3.8.6-1.glibc2.12.x86_64.rpm | cpio -id
```

The mpss-core RPM does not contain any files.

**Comment by PushPioneer** [comment]
Now it works. Thank you. The only problem now is that it dosn't detect my Xeon Phi anymore neither `dmesg` or `lspci` show my Xeon Phi but this should be a different problem. I am probably going to reopen this issue later with a full install-script for ubuntu 18.04. And again Thank you very much.

**Comment by jjkeijser** [comment]
Note that if the Xeon Phi drops off the PCIe bus when you boot it up, then most likely you have a power supply problem - the motherboard needs to be able to supply 300W to the card at boot up.  This was one of the many hardware issues with the Xeon Phis (first and second generation) when they came out.
